### ISSUE TITLE
Implement OAuth2 token validation

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp.Monolith#18]
# Descriptions
Implement stateless OAuth2.0 authentication by implementing ITokenValidator from the [Owin.StatelessAuth](https://www.nuget.org/packages/Owin.StatelessAuth/) nuget package

# Tasks
- [x] Add Validator that implements ITokenValidator
- [x] Add init method that retrieves signing keys from selected endpoint
- [x] Implement the ValidateUser method. This method should validate the token then populate the ClaimsPrinciple
- [x] Add AutoInjection header
