### ISSUE TITLE
Update Cake build script

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp.Monolith#19]
# Description
The build script for Monolith is badly out of date when compared to VaraniumSharp. Update the build script to bring it in line with what is currently in VaraniumSharp or Initiator.

# Tasks
- [x] Update build script
- [x] Create Codefactor project
- [x] Create Coveralls project
- [x] Add Nuget badge to readme
- [x] Add Build badge to readme
- [x] Add Coverage badge to readme
- [x] Add Codefactor to readme
- [x] Add DocFX documentation
- [x] Ensure bot has access to publish documentation
